### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by owengoodwin** [elam3/cs177.p1.g3#7]
Need to upload finished documentation so we can submit.

**Comment by elam3** [comment]
@owengoodwin 
https://github.com/elam3/cs177.p1.g3/blob/master/admin.html
https://github.com/elam3/cs177.p1.g3/blob/master/help.html

**Comment by owengoodwin** [comment]
http://htmlpreview.github.io/?https://github.com/elam3/cs177.p1.g3/blob/master/help.html
